-- MySQL Script generated by MySQL Workbench
-- 05/23/18 09:03:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_asitri
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_asitri
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_asitri` DEFAULT CHARACTER SET latin1 ;
USE `db_asitri` ;

-- -----------------------------------------------------
-- Table `db_asitri`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_asitri`.`area` (
  `idArea` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombreArea` VARCHAR(60) NOT NULL COMMENT '',
  `descripcionArea` TEXT NOT NULL COMMENT '',
  PRIMARY KEY (`idArea`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 477
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_asitri`.`docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_asitri`.`docente` (
  `idDoc` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `ciDoc` VARCHAR(15) NOT NULL COMMENT '',
  `nombreDoc` VARCHAR(60) NOT NULL COMMENT '',
  `apePaternoDoc` VARCHAR(60) NOT NULL COMMENT '',
  `apeMaternoDoc` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `emailDoc` VARCHAR(50) NOT NULL COMMENT '',
  `telefonoDoc` DECIMAL(10,0) NOT NULL COMMENT '',
  `tituloDoc` VARCHAR(20) NULL DEFAULT NULL COMMENT '',
  `cargaHoraria` VARCHAR(40) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idDoc`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 84
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_asitri`.`modalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_asitri`.`modalidad` (
  `idModalidad` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombreMod` VARCHAR(45) NOT NULL COMMENT '',
  `descripcionMod` TEXT NOT NULL COMMENT '',
  PRIMARY KEY (`idModalidad`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_asitri`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_asitri`.`proyecto` (
  `idProyecto` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `titulo` VARCHAR(50) NOT NULL COMMENT '',
  `objetivos` TEXT NOT NULL COMMENT '',
  `descripcion` TEXT NOT NULL COMMENT '',
  `fechaIni` DATE NULL DEFAULT NULL COMMENT '',
  `fechaFin` DATE NULL DEFAULT NULL COMMENT '',
  `periodo` VARCHAR(30) NOT NULL COMMENT '',
  `sesionDeConsejo` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `idModalidad` INT(2) NOT NULL COMMENT '',
  `estadoProyecto` ENUM('terminado', 'pendiente', 'eliminado') NOT NULL COMMENT '',
  `fechaRegistroProy` TEXT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idProyecto`)  COMMENT '',
  INDEX `fk_proyecto_modalidad1_idx` (`idModalidad` ASC)  COMMENT '',
  CONSTRAINT `fk_proyecto_modalidad1`
    FOREIGN KEY (`idModalidad`)
    REFERENCES `db_asitri`.`modalidad` (`idModalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3303
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_asitri`.`asignacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_asitri`.`asignacion` (
  `idAsig` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `rol` ENUM('tribunal', 'tutor') CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL COMMENT '',
  `idProyecto` INT(11) NOT NULL COMMENT '',
  `idDoc` INT(11) NOT NULL COMMENT '',
  `estado` ENUM('activo', 'inactivo') NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idAsig`)  COMMENT '',
  INDEX `fk_Asignacion_Proyecto1_idx` (`idProyecto` ASC)  COMMENT '',
  INDEX `fk_Asignacion_Docente1_idx` (`idDoc` ASC)  COMMENT '',
  CONSTRAINT `fk_Asignacion_Docente1`
    FOREIGN KEY (`idDoc`)
    REFERENCES `db_asitri`.`docente` (`idDoc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignacion_Proyecto1`
    FOREIGN KEY (`idProyecto`)
    REFERENCES `db_asitri`.`proyecto` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_asitri`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_asitri`.`carrera` (
  `idCarrera` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombreCarrera` VARCHAR(60) NOT NULL COMMENT '',
  PRIMARY KEY (`idCarrera`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_asitri`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_asitri`.`estudiante` (
  `idEstudiante` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `ciEst` VARCHAR(15) NOT NULL COMMENT '',
  `nombreEst` VARCHAR(60) NOT NULL COMMENT '',
  `apellidoEst` VARCHAR(60) NOT NULL COMMENT '',
  `emailEst` VARCHAR(50) NOT NULL COMMENT '',
  `telefono` DECIMAL(10,0) NOT NULL COMMENT '',
  `idCarrera` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`idEstudiante`)  COMMENT '',
  INDEX `fk_estudiante_carrera1_idx` (`idCarrera` ASC)  COMMENT '',
  CONSTRAINT `fk_estudiante_carrera1`
    FOREIGN KEY (`idCarrera`)
    REFERENCES `db_asitri`.`carrera` (`idCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_asitri`.`pertenece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_asitri`.`pertenece` (
  `idPertenece` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idCarrera` INT(11) NOT NULL COMMENT '',
  `idDoc` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`idPertenece`)  COMMENT '',
  INDEX `fk_Pertenece_Carrera1_idx` (`idCarrera` ASC)  COMMENT '',
  INDEX `fk_Pertenece_Docente1_idx` (`idDoc` ASC)  COMMENT '',
  CONSTRAINT `fk_Pertenece_Carrera1`
    FOREIGN KEY (`idCarrera`)
    REFERENCES `db_asitri`.`carrera` (`idCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pertenece_Docente1`
    FOREIGN KEY (`idDoc`)
    REFERENCES `db_asitri`.`docente` (`idDoc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_asitri`.`proyecto_has_area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_asitri`.`proyecto_has_area` (
  `idProyecto` INT(11) NOT NULL COMMENT '',
  `idArea` INT(11) NOT NULL COMMENT '',
  `tipo` ENUM('area', 'subarea') NULL COMMENT '',
  PRIMARY KEY (`idProyecto`, `idArea`)  COMMENT '',
  INDEX `fk_proyecto_has_area_area1_idx` (`idArea` ASC)  COMMENT '',
  INDEX `fk_proyecto_has_area_proyecto1_idx` (`idProyecto` ASC)  COMMENT '',
  CONSTRAINT `fk_proyecto_has_area_area1`
    FOREIGN KEY (`idArea`)
    REFERENCES `db_asitri`.`area` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyecto_has_area_proyecto1`
    FOREIGN KEY (`idProyecto`)
    REFERENCES `db_asitri`.`proyecto` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_asitri`.`renuncia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_asitri`.`renuncia` (
  `idRenuncia` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `fechaRenuncia` DATE NOT NULL COMMENT '',
  `motivosRenuncia` TEXT NOT NULL COMMENT '',
  `idAsig` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`idRenuncia`)  COMMENT '',
  INDEX `fk_Renuncia_Asignacion1_idx` (`idAsig` ASC)  COMMENT '',
  CONSTRAINT `fk_Renuncia_Asignacion1`
    FOREIGN KEY (`idAsig`)
    REFERENCES `db_asitri`.`asignacion` (`idAsig`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_asitri`.`tiene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_asitri`.`tiene` (
  `idTiene` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idArea` INT(11) NOT NULL COMMENT '',
  `idDoc` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`idTiene`)  COMMENT '',
  INDEX `fk_Tiene_Area_idx` (`idArea` ASC)  COMMENT '',
  INDEX `fk_Tiene_Docente1_idx` (`idDoc` ASC)  COMMENT '',
  CONSTRAINT `fk_Tiene_Area`
    FOREIGN KEY (`idArea`)
    REFERENCES `db_asitri`.`area` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tiene_Docente1`
    FOREIGN KEY (`idDoc`)
    REFERENCES `db_asitri`.`docente` (`idDoc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 199
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_asitri`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_asitri`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(50) NOT NULL COMMENT '',
  `email` VARCHAR(50) NOT NULL COMMENT '',
  `password` VARCHAR(255) NOT NULL COMMENT '',
  `remember_token` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  `created_at` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  `updated_at` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_asitri`.`proyecto_estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_asitri`.`proyecto_estudiante` (
  `idProyecto` INT(11) NOT NULL COMMENT '',
  `idEstudiante` INT(11) NOT NULL COMMENT '',
  `estado` ENUM('activo', 'inactivo') NOT NULL DEFAULT 'activo' COMMENT '',
  INDEX `fk_proyecto_estudiante_proyecto1_idx` (`idProyecto` ASC)  COMMENT '',
  INDEX `fk_proyecto_estudiante_estudiante1_idx` (`idEstudiante` ASC)  COMMENT '',
  CONSTRAINT `fk_proyecto_estudiante_proyecto1`
    FOREIGN KEY (`idProyecto`)
    REFERENCES `db_asitri`.`proyecto` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyecto_estudiante_estudiante1`
    FOREIGN KEY (`idEstudiante`)
    REFERENCES `db_asitri`.`estudiante` (`idEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
